const quotes = [
    // Stoic Quotes (100)
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "What need is there to weep over parts of life? The whole of it calls for tears. - Seneca",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. - Epictetus",
    "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
    "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "He who lives in harmony with himself lives in harmony with the universe. - Marcus Aurelius",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "We suffer more often in imagination than in reality. - Seneca",
    "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "No man was ever wise by chance. - Seneca",
    "You act like mortals in all that you fear, and like immortals in all that you desire. - Seneca",
    "Don’t explain your philosophy. Embody it. - Epictetus",
    "First say to yourself what you would be; and then do what you have to do. - Epictetus",
    "It’s not what happens to you, but how you react to it that matters. - Epictetus",
    "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Epictetus",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "Make the best use of what is in your power, and take the rest as it happens. - Epictetus",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. - Marcus Aurelius",
    "Accept the things to which fate binds you, and love the people with whom fate brings you together. - Marcus Aurelius",
    "To live a good life: We have the potential for it. If we can learn to be indifferent to what makes no difference. - Marcus Aurelius",
    "Death smiles at us all; all we can do is smile back. - Marcus Aurelius",
    "What stands in the way becomes the way. - Marcus Aurelius",
    "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
    "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
    "While we are postponing, life speeds by. - Seneca",
    "As is a tale, so is life: not how long it is, but how good it is, is what matters. - Seneca",
    "Life is like a play: it’s not the length, but the excellence of the acting that matters. - Seneca",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "He who fears death will never do anything worthy of a living man. - Seneca",
    "Every new beginning comes from some other beginning’s end. - Seneca",
    "Man is affected not by events, but by the view he takes of them. - Epictetus",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Epictetus",
    "No person has the power to have everything they want, but it is in their power not to want what they don’t have. - Seneca",
    "The whole future lies in uncertainty: live immediately. - Seneca",
    "To be everywhere is to be nowhere. - Seneca",
    "People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy. - Seneca",
    "If a man knows not to which port he sails, no wind is favorable. - Seneca",
    "Circumstances don’t make the man, they only reveal him to himself. - Epictetus",
    "You become what you give your attention to. - Epictetus",
    "Caretake this moment. Immerse yourself in its particulars. - Epictetus",
    "To live happily is an inward power of the soul. - Marcus Aurelius",
    "The art of living is more like wrestling than dancing. - Marcus Aurelius",
    "Think of yourself as dead. You have lived your life. Now take what’s left and live it properly. - Marcus Aurelius",
    "Nothing happens to any man that he is not formed by nature to bear. - Marcus Aurelius",
    "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
    "No great thing is created suddenly. - Epictetus",
    "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. - Epictetus",
    "When you arise in the morning, think of what a precious privilege it is to be alive. - Marcus Aurelius",
    "How much time he gains who does not look to see what his neighbor says or does or thinks. - Marcus Aurelius",
    "Reject your sense of injury and the injury itself disappears. - Marcus Aurelius",
    "Loss is nothing else but change, and change is Nature’s delight. - Marcus Aurelius",
    "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look. - Marcus Aurelius",
    "It is in your power to withdraw yourself whenever you desire. - Marcus Aurelius",
    "Live out your life in truth and justice, tolerant of those who are neither true nor just. - Marcus Aurelius",
    "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane. - Marcus Aurelius",
    "A man’s worth is no greater than his ambitions. - Marcus Aurelius",
    "Let not your mind run on what you lack as much as on what you have already. - Marcus Aurelius",
    "Religion is to do right. It is to love, it is to serve, it is to think, it is to be humble. - Seneca",
    "A gem cannot be polished without friction, nor a man perfected without trials. - Seneca",
    "True happiness is to enjoy the present, without anxious dependence upon the future. - Seneca",
    "We are more often frightened than hurt; and we suffer more from imagination than from reality. - Seneca",
    "Life is very short and anxious for those who forget the past, neglect the present, and fear the future. - Seneca",
    "The bravest sight in the world is to see a great man struggling against adversity. - Seneca",
    "Throw me to the wolves and I will return leading the pack. - Seneca",
    "What is harder than rock? What is softer than water? Yet hard rocks are hollowed out by soft water. - Seneca",
    "There is no easy way from the earth to the stars. - Seneca",
    "The mind that is anxious about future events is miserable. - Seneca",
    "Any person capable of angering you becomes your master. - Epictetus",
    "No man is free who is not master of himself. - Epictetus",
    "Know, first, who you are, and then adorn yourself accordingly. - Epictetus",
    "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
    "The greater the difficulty, the more glory in surmounting it. - Epictetus",
    "Attach yourself to what is spiritually superior, regardless of what other people think or do. - Epictetus",
    "Practice yourself, for heaven’s sake, in little things; and thence proceed to greater. - Epictetus",
    "Be silent for the most part, or say only what is necessary and in few words. - Epictetus",
    "The life of man is of no greater duration than the breath of his nostrils. - Marcus Aurelius",
    "When you have assumed these names—good, modest, truthful, rational, calm, magnanimous—take care that you do not change them. - Marcus Aurelius",
    "The memory of everything is very soon overwhelmed in time. - Marcus Aurelius",
    "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
    "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too. - Marcus Aurelius",
    "Give yourself a gift: the present moment. - Marcus Aurelius",
    "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it. - Marcus Aurelius",
    "Pass through this brief patch of time in harmony with nature, and end your journey content. - Marcus Aurelius",
    "The only wealth which you will keep forever is the wealth you have given away. - Marcus Aurelius",
    "Anger cannot be dishonest. - Marcus Aurelius",
    "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are. - Marcus Aurelius",
    "Do every act of your life as if it were your last. - Marcus Aurelius",
    "Be like the cliff against which the waves continually break; but it stands firm and tames the fury of the water around it. - Marcus Aurelius",
    "In the morning, when you rise unwillingly, let this thought be present: I am rising to the work of a human being. - Marcus Aurelius",
    "Time is a sort of river of passing events, and strong is its current. - Epictetus",
    "The thing in itself is not terrible; it is our opinion of it that makes it so. - Epictetus",
    "If evil be spoken of you and it be true, correct yourself; if it be a lie, laugh at it. - Epictetus",
    "When you are offended at any man’s fault, turn to yourself and study your own failings. - Epictetus",
    "You are a little soul carrying around a corpse. - Epictetus",

    // Buddhist Quotes (100)
    "The root of suffering is attachment. - Buddha",
    "Peace comes from within. Do not seek it without. - Buddha",
    "The mind is everything. What you think you become. - Buddha",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Three things cannot be long hidden: the sun, the moon, and the truth. - Buddha",
    "You only lose what you cling to. - Buddha",
    "Hatred does not cease by hatred, but only by love; this is the eternal rule. - Buddha",
    "To understand everything is to forgive everything. - Buddha",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path. - Buddha",
    "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. - Buddha",
    "The way is not in the sky. The way is in the heart. - Buddha",
    "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned. - Buddha",
    "There is no path to happiness: happiness is the path. - Buddha",
    "Better than a thousand hollow words is one word that brings peace. - Buddha",
    "All that we are is the result of what we have thought. - Buddha",
    "An idea that is developed and put into action is more important than an idea that exists only as an idea. - Buddha",
    "Even death is not to be feared by one who has lived wisely. - Buddha",
    "The tongue like a sharp knife… Kills without drawing blood. - Buddha",
    "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you. - Buddha",
    "To conquer oneself is a greater task than conquering others. - Buddha",
    "Your purpose in life is to find your purpose and give your whole heart and soul to it. - Buddha",
    "There is nothing more dreadful than the habit of doubt. - Buddha",
    "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly. - Buddha",
    "Every morning we are born again. What we do today is what matters most. - Buddha",
    "What we think, we become. - Buddha",
    "Pain is certain, suffering is optional. - Buddha",
    "The only real failure in life is not to be true to the best one knows. - Buddha",
    "A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise. - Buddha",
    "You will not be punished for your anger; you will be punished by your anger. - Buddha",
    "If you light a lamp for somebody, it will also brighten your path. - Buddha",
    "Work out your own salvation. Do not depend on others. - Buddha",
    "To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear. - Buddha",
    "Just as a snake sheds its skin, we must shed our past over and over again. - Buddha",
    "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them? - Buddha",
    "Radiate boundless love towards the entire world. - Buddha",
    "The foot feels the foot when it feels the ground. - Buddha",
    "If you do not change direction, you may end up where you are heading. - Buddha",
    "A disciplined mind brings happiness. - Buddha",
    "Purity or impurity depends on oneself, no one can purify another. - Buddha",
    "Nothing ever exists entirely alone; everything is in relation to everything else. - Buddha",
    "There is no fire like passion, there is no shark like hatred, there is no snare like folly, there is no torrent like greed. - Buddha",
    "Let us rise up and be thankful, for if we didn’t learn a lot today, at least we learned a little. - Buddha",
    "An insincere and evil friend is more to be feared than a wild beast; a wild beast may wound your body, but an evil friend will wound your mind. - Buddha",
    "Whatever words we utter should be chosen with care for people will hear them and be influenced by them for good or ill. - Buddha",
    "If we could see the miracle of a single flower clearly, our whole life would change. - Buddha",
    "The trouble is, you think you have time. - Buddha",
    "Believe nothing, no matter where you read it, or who said it, unless it agrees with your own reason and your own common sense. - Buddha",
    "Be where you are; otherwise you will miss your life. - Buddha",
    "Patience is key. Remember: A jug fills drop by drop. - Buddha",
    "The wise man makes an island of himself that no flood can overwhelm. - Buddha",
    "All wrong-doing arises because of mind. If mind is transformed can wrong-doing remain? - Buddha",
    "He who loves 50 people has 50 woes; he who loves no one has no woes. - Buddha",
    "Chaos is inherent in all compounded things. Strive on with diligence. - Buddha",
    "It is better to travel well than to arrive. - Buddha",
    "Even as a solid rock is unshaken by the wind, so are the wise unshaken by praise or blame. - Buddha",
    "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good. - Buddha",
    "The greatest prayer is patience. - Buddha",
    "If you find no one to support you on the spiritual path, walk alone. - Buddha",
    "To be idle is a short road to death and to be diligent is a way of life. - Buddha",
    "Meditation brings wisdom; lack of meditation leaves ignorance. - Buddha",
    "When you realize how perfect everything is, you will tilt your head back and laugh at the sky. - Buddha",
    "There is no fear for one whose mind is not filled with desires. - Buddha",
    "Happiness does not depend on what you have or who you are. It solely relies on what you think. - Buddha",
    "A fool who knows his foolishness is wise at least to that extent, but a fool who thinks himself wise is a fool indeed. - Buddha",
    "Nothing can harm you as much as your own thoughts unguarded. - Buddha",
    "Speak only endearing speech, speech that is welcomed. - Buddha",
    "Do not overrate what you have received, nor envy others. He who envies others does not obtain peace of mind. - Buddha",
    "Live every act fully, as if it were your last. - Buddha",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. - Buddha",
    "One moment can change a day, one day can change a life, and one life can change the world. - Buddha",
    "The past is already gone, the future is not yet here. There’s only one moment for you to live. - Buddha",
    "When you like a flower, you just pluck it. But when you love a flower, you water it daily. - Buddha",
    "Teach this triple truth to all: A generous heart, kind speech, and a life of service and compassion are the things which renew humanity. - Buddha",
    "Happiness will never come to those who fail to appreciate what they already have. - Buddha",
    "The world is afflicted by death and decay. But the wise do not grieve, having realized the nature of the world. - Buddha",
    "If anything is worth doing, do it with all your heart. - Buddha",
    "It is a man’s own mind, not his enemy or foe, that lures him to evil ways. - Buddha",
    "Be a lamp unto yourself. Work out your liberation with diligence. - Buddha",
    "Your worst enemy cannot harm you as much as your own unguarded thoughts. - Buddha",
    "You yourself, as much as anybody in the entire universe, deserve your love and affection. - Buddha",
    "People with opinions just go around bothering one another. - Buddha",
    "Wear your ego like a loose fitting garment. - Buddha",
    "The one who has conquered himself is a far greater hero than he who has defeated a thousand times a thousand men. - Buddha",
    "What you are is what you have been. What you’ll be is what you do now. - Buddha",
    "With gentleness overcome anger. With generosity overcome meanness. With truth overcome deceit. - Buddha",
    "In separateness lies the world’s greatest misery; in compassion lies the world’s true strength. - Buddha",
    "Anger will never disappear so long as thoughts of resentment are cherished in the mind. - Buddha",
    "To live a pure unselfish life, one must count nothing as one’s own in the midst of abundance. - Buddha",
    "Silence the angry man with love. Silence the ill-natured man with kindness. - Buddha",
    "Do not look for a sanctuary in anyone except yourself. - Buddha",
    "Better it is to live one day seeing the supreme truth than to live a hundred years without seeing it. - Buddha",
    "The calmed say that what is well-spoken is best; second, that one should say what is right, not unrighteous. - Buddha",
    "Ceasing to do evil, cultivating the good, purifying the heart: this is the teaching of the Buddhas. - Buddha",
    "Conquer anger with non-anger. Conquer badness with goodness. - Buddha",
    "Should you find a wise critic to point out your faults, follow him as you would a guide to hidden treasure. - Buddha",
    "Like a fine flower, beautiful to look at but without scent, fine words are fruitless in a man who does not act in accordance with them. - Buddha",
    "On life’s journey faith is nourishment, virtuous deeds are a shelter, wisdom is the light by day and right mindfulness is the protection by night. - Buddha",
    "With fools, there is no companionship. Rather than to live with men who are selfish, vain, and obstinate, let a man walk alone. - Buddha",

    // Sadhguru Quotes (50)
    "The only way out is in. - Sadhguru",
    "If you choose to live consciously, every aspect of your life can become a process of liberation. - Sadhguru",
    "The mind is like a mirror. If you keep it clean, it will reflect life as it is. - Sadhguru",
    "Life is a process, not a problem. The question is only, have you prepared yourself for the process or not. - Sadhguru",
    "Do not try to fix whatever comes in your life. Fix yourself in such a way that whatever comes, you will be fine. - Sadhguru",
    "When you are in a great hurry to do something, you are only postponing your own joy. - Sadhguru",
    "The most beautiful moments in life are moments when you are expressing your joy, not when you are seeking it. - Sadhguru",
    "If you resist change, you resist life. - Sadhguru",
    "The fear is simply because you are suffering with something that does not exist. - Sadhguru",
    "The source of creation is within you. If you allow it to function, everything will be okay. - Sadhguru",
    "The quality of your life depends on how well you manage your body, mind, emotions, and energy. - Sadhguru",
    "Happiness is not something you pursue; it is something you allow. - Sadhguru",
    "If you are suffering your own mind, it is because you have not taken charge of it. - Sadhguru",
    "The spiritual journey is from the tyranny of the mind to the freedom of consciousness. - Sadhguru",
    "The moment you are identified with something that you are not, you are distorting reality. - Sadhguru",
    "The only thing that stands between you and your wellbeing is a simple fact: you have allowed your thoughts and emotions to take instruction from the outside rather than the inside. - Sadhguru",
    "Your body and mind are just accessories. The real you is beyond both. - Sadhguru",
    "If you want to know the joy of living, you must learn to live without fear. - Sadhguru",
    "The greatest adventure in life is to discover who you truly are. - Sadhguru",
    "The way you think, feel, and act is the way your life will unfold. - Sadhguru",
    "You cannot suffer the past or the future because they do not exist. What you are suffering is your memory and your imagination. - Sadhguru",
    "The sign of intelligence is that you are constantly wondering. Idiots are always dead sure about everything. - Sadhguru",
    "Whatever you do, do it with utmost involvement, and it will lead you to your ultimate nature. - Sadhguru",
    "The purpose of life is to live it totally, without holding back. - Sadhguru",
    "You don’t have to be better than anyone else; you just have to be the best version of yourself. - Sadhguru",
    "The only way to experience true wellbeing is to turn inward. - Sadhguru",
    "If you handle your mind, you handle your life. If you do not handle your mind, your life will handle you. - Sadhguru",
    "The moment you pay substantial attention to what you call ‘myself,’ you will see there is no such thing as ‘myself.’ - Sadhguru",
    "The only bondage is the prison of your own mind. - Sadhguru",
    "The greatest gift you can give to the world is to be a joyful human being. - Sadhguru",
    "Life is not about getting somewhere; it is about being fully present wherever you are. - Sadhguru",
    "When you are in touch with your own existence, you don’t need to believe anything. You simply know. - Sadhguru",
    "The only solution to all your problems is to turn inwards. - Sadhguru",
    "If you are joyful by your own nature, you will not suffer anything that happens in life. - Sadhguru",
    "The quality of your life is determined by how you respond to situations, not by the situations themselves. - Sadhguru",
    "To be peaceful and joyful is not a denial of life; it is the very affirmation of life. - Sadhguru",
    "The only way to live sensibly is to live without conclusions. - Sadhguru",
    "When you are no longer trying to be something, you will naturally be everything you need to be. - Sadhguru",
    "The more you are identified with your mind, the more you suffer. - Sadhguru",
    "Every human being is capable of living in a way that the whole world looks up to them. - Sadhguru",
    "If you want to live a life of fulfillment, you must live with intensity and involvement. - Sadhguru",
    "The moment you take responsibility for who you are, you will naturally become a source of joy. - Sadhguru",
    "The spiritual process is not about becoming something; it is about becoming nothing. - Sadhguru",
    "The only thing that separates you from the divine is your unwillingness to look beyond your own limitations. - Sadhguru",
    "If you are rooted in reality, there will be no fear, no matter what happens. - Sadhguru",
    "Life is just a certain amount of time and energy. How you use it determines the quality of your life. - Sadhguru",
    "The only way to know life is to experience it, not to think about it. - Sadhguru",
    "The greatest crime is to live a life of mediocrity. - Sadhguru",
    "Your peace and joy are not dependent on what is happening around you but on how you are within yourself. - Sadhguru",
    "If you want to make a difference in the world, the first thing you must do is make a difference within yourself. - Sadhguru"
];
